import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/index.js';
test('auth, consent, RBAC, idempotent sync, revocation and deletion',async()=>{const {app,db}=createApp(':memory:');const server=app.listen(0);await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api';
async function req(path,method='GET',body,cookie,origin){const r=await fetch(base+path,{method,headers:{'content-type':'application/json','x-smriti-client':'test',...(cookie?{cookie}:{}),...(origin?{origin}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
try{const p=await req('/auth/signup','POST',{email:'patient@example.test',name:'Patient',password:'a-long-password',role:'patient',consent:true});assert.equal(p.status,201);const c=await req('/auth/signup','POST',{email:'care@example.test',name:'Carer',password:'a-long-password',role:'caregiver',consent:true});const id=p.data.id;assert.equal((await req('/me','GET',undefined,p.cookie)).status,200);assert.equal((await req('/patients/'+id+'/records','GET',undefined,c.cookie)).status,403);assert.equal((await req('/invites','POST',{consent:false},p.cookie)).status,403);assert.equal((await req('/invites','POST',{consent:true},p.cookie,'https://evil.example')).status,403);
const invitation=await req('/invites','POST',{consent:true},p.cookie);assert.equal((await req('/links','POST',{code:invitation.data.code},c.cookie)).status,200);assert.equal((await req('/links','POST',{code:invitation.data.code},c.cookie)).status,400);
const event={eventId:randomUUID(),id:randomUUID(),kind:'score',op:'put',data:{game:'memory',accuracy:.8,latency:4000,level:1,at:Date.now(),rounds:5}};assert.equal((await req('/patients/'+id+'/events','POST',event,c.cookie)).status,403);assert.equal((await req('/patients/'+id+'/events','POST',event,p.cookie)).status,200);assert.equal((await req('/patients/'+id+'/events','POST',event,p.cookie)).data.duplicate,true);assert.equal((await req('/patients/'+id+'/records','GET',undefined,c.cookie)).data.length,1);
const garden={eventId:randomUUID(),id:'garden-test',kind:'score',op:'put',data:{game:'garden',campaignLevel:1,level:1,rounds:3,moves:3,stars:3,hints:0,seconds:10,accuracy:1,latency:3333,at:Date.now()}};assert.equal((await req('/patients/'+id+'/events','POST',garden,p.cookie)).status,200);const rows=(await req('/patients/'+id+'/records','GET',undefined,c.cookie)).data;assert.ok(rows.some(x=>x.id==='garden-test'));assert.equal((await req('/patients/'+id+'/events','POST',{...garden,eventId:randomUUID(),data:{...garden.data,stars:1}},p.cookie)).status,400);
const location={eventId:randomUUID(),id:'latest-location',kind:'location',op:'put',data:{lat:26,lng:91,accuracy:10,at:Date.now()}};assert.equal((await req('/patients/'+id+'/events','POST',location,p.cookie)).status,403);const settings={eventId:randomUUID(),id:'settings',kind:'settings',op:'put',data:{locationConsent:true,phone:''}};assert.equal((await req('/patients/'+id+'/events','POST',settings,p.cookie)).status,200);assert.equal((await req('/patients/'+id+'/events','POST',location,p.cookie)).status,200);assert.equal((await req('/patients/'+id+'/events','POST',{...settings,eventId:randomUUID(),data:{locationConsent:false,phone:''}},p.cookie)).status,200);assert.ok(!(await req('/patients/'+id+'/records','GET',undefined,p.cookie)).data.some(x=>x.kind==='location'));
assert.equal((await req('/links/'+c.data.id,'DELETE',undefined,p.cookie)).status,200);assert.equal((await req('/patients/'+id+'/records','GET',undefined,c.cookie)).status,403);assert.equal((await req('/account','DELETE',{confirm:'DELETE'},p.cookie)).status,200);assert.equal((await req('/me','GET',undefined,p.cookie)).status,401);assert.equal(db.prepare('SELECT count(*) AS n FROM records WHERE patient=?').get(id).n,0);
}finally{await new Promise(r=>server.close(r));db.close();}});
