import express from 'express';
import helmet from 'helmet';
import {rateLimit} from 'express-rate-limit';
import {DatabaseSync} from 'node:sqlite';
import {scryptSync,randomBytes,randomUUID,timingSafeEqual,createHash} from 'node:crypto';
import {readFileSync,mkdirSync,existsSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {z} from 'zod';
import {scoreSchema} from './score-schema.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const sha=s=>createHash('sha256').update(s).digest('hex');
const publicUser=u=>({id:u.id,name:u.name,role:u.role,email:u.email});
const passwordHash=p=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex');};
const matches=(p,h)=>{const [s,k]=h.split(':');return timingSafeEqual(Buffer.from(k,'hex'),scryptSync(p,s,64));};
const text=z.string().trim().min(1).max(500);
const point={lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)};
const schemas={score:scoreSchema,reminder:z.object({title:text,due:z.number(),done:z.boolean(),notified:z.boolean().optional()}),place:z.object({...point,name:text,cue:text,radius:z.number().min(50).max(10000)}),family:z.object({name:text,relation:text,age:z.number().min(0).max(120).optional(),occupation:text.optional(),phone:z.string().regex(/^[+0-9 ()-]{0,25}$/).optional()}),location:z.object({...point,accuracy:z.number().min(0),at:z.number()}),alert:z.object({type:z.enum(['sos','geofence','journey-deviation']),message:text,at:z.number(),ack:z.boolean(),location:z.object({...point,accuracy:z.number().min(0),at:z.number()}).optional(),destination:z.object({name:text,lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)}).optional(),voiceDataUrl:z.string().max(50000).optional()}),journey:z.object({active:z.boolean(),startedAt:z.number().optional(),endedAt:z.number().optional(),stepIndex:z.number().int().min(0).optional(),destination:z.object({name:text,lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)}).optional(),route:z.object({geometry:z.object({type:z.string(),coordinates:z.array(z.array(z.number())).min(2)}),distance:z.number().min(0),duration:z.number().min(0),steps:z.array(z.object({instruction:text,name:z.string().max(200).optional(),distance:z.number().min(0),location:z.array(z.number()).length(2).optional(),maneuver:z.unknown().optional()}))}).optional()}),settings:z.object({locationConsent:z.boolean(),phone:z.string().regex(/^[+0-9 ()-]{0,25}$/),name:text.optional(),age:z.number().min(0).max(120).optional(),voiceDataUrl:z.string().max(50000).optional(),shareViaId:z.boolean().optional()}),report:z.object({name:text,category:z.enum(['General','Blood Test','Prescription','Scan/Imaging','Vaccination','Other']),notes:z.string().trim().max(1000).optional(),fileName:z.string().trim().min(1).max(200),fileType:z.enum(['image/jpeg','image/png','image/webp','image/gif','application/pdf']),fileData:z.string().min(1).max(7000000),uploadedBy:z.enum(['patient','caregiver']),uploaderName:text.optional(),at:z.number()}),memory:z.object({title:text,photoDataUrl:z.string().min(1).max(2000000),addedBy:z.enum(['patient','caregiver']),memberName:z.string().trim().max(200).optional(),at:z.number()})};
export function createApp(databasePath=process.env.DATABASE_PATH||resolve(root,'data/smritisaathi.db')){
 if(databasePath!==':memory:')mkdirSync(dirname(resolve(databasePath)),{recursive:true});
 const db=new DatabaseSync(databasePath);db.exec(readFileSync(resolve(root,'server/schema.sql'),'utf8'));
 const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'data:','https://*.tile.openstreetmap.org'],'connect-src':["'self'",'https://*.googleapis.com','https://*.firebaseinstallations.googleapis.com','https://*.openstreetmap.org','https://router.project-osrm.org'],'script-src':["'self'"],'style-src':["'self'","'unsafe-inline'"]}}}));
 app.use('/api',(_q,r,n)=>{r.set('Cache-Control','no-store');n();});
 app.use('/api',(q,r,n)=>{if(!['GET','HEAD','OPTIONS'].includes(q.method)){const origin=q.get('origin');const allowed=(process.env.APP_ORIGIN||'http://localhost:5173,http://127.0.0.1:5173').split(',');if(origin&&!allowed.includes(origin))return r.status(403).json({error:'Origin not allowed'});if(!q.get('x-smriti-client'))return r.status(403).json({error:'Client header required'});}n();});
 app.use(express.json({limit:'8mb'}));
 app.use('/api',rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-7',legacyHeaders:false}));
 app.use('/api/auth',rateLimit({windowMs:15*60000,limit:40,standardHeaders:'draft-7',legacyHeaders:false}));
 const audit=(actor,action,target)=>db.prepare('INSERT INTO audit(actor,action,target,at) VALUES(?,?,?,?)').run(actor,action,target||null,Date.now());
 const issue=(r,u)=>{const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(sha(token),u.id,Date.now()+7*86400000);r.cookie('smriti_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:7*86400000,path:'/'});return publicUser(u);};
 app.get('/api/health',(_q,r)=>r.json({ok:true}));
 app.post('/api/auth/signup',(q,r)=>{const v=z.object({email:z.email().max(200),password:z.string().min(10).max(128),name:text,role:z.enum(['patient','caregiver']),consent:z.literal(true)}).parse(q.body);const email=v.email.toLowerCase();if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return r.status(409).json({error:'Account already exists'});const u={...v,email,id:randomUUID()};db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(u.id,email,u.name,passwordHash(v.password),u.role,Date.now());audit(u.id,'consent:account:v1',u.id);r.status(201).json(issue(r,u));});
 app.post('/api/auth/login',(q,r)=>{const v=z.object({email:z.string().max(200),password:z.string().max(128)}).parse(q.body);const u=db.prepare('SELECT * FROM users WHERE email=?').get(v.email.toLowerCase());if(!u||!matches(v.password,u.password))return r.status(401).json({error:'Email or password is incorrect'});r.json(issue(r,u));});
 app.use('/api',(q,r,n)=>{const token=(q.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('smriti_session='))?.slice(15);const session=token&&db.prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').get(sha(token),Date.now());if(!session)return r.status(401).json({error:'Please sign in online'});q.user=db.prepare('SELECT * FROM users WHERE id=?').get(session.user_id);q.session=sha(token);n();});
 app.get('/api/me',(q,r)=>r.json(publicUser(q.user)));
 app.post('/api/auth/logout',(q,r)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(q.session);r.clearCookie('smriti_session',{path:'/'});r.json({ok:true});});
 const access=(q,r,n)=>{q.patient=q.params.patient;if(q.user.id===q.patient&&q.user.role==='patient')return n();if(q.user.role==='caregiver'&&db.prepare('SELECT 1 FROM links WHERE patient=? AND caregiver=?').get(q.patient,q.user.id))return n();return r.status(403).json({error:'Patient consent and linking required'});};
 app.get('/api/links',(q,r)=>{const sql=q.user.role==='patient'?'SELECT u.id,u.name,u.role FROM links l JOIN users u ON u.id=l.caregiver WHERE l.patient=?':'SELECT u.id,u.name,u.role FROM links l JOIN users u ON u.id=l.patient WHERE l.caregiver=?';r.json(db.prepare(sql).all(q.user.id));});
 app.post('/api/invites',(q,r)=>{if(q.user.role!=='patient'||q.body.consent!==true)return r.status(403).json({error:'Patient sharing consent required'});const code=randomBytes(8).toString('hex');db.prepare('DELETE FROM invites WHERE patient=?').run(q.user.id);db.prepare('INSERT INTO invites VALUES(?,?,?)').run(sha(code),q.user.id,Date.now()+600000);audit(q.user.id,'consent:share:v1',q.user.id);r.json({code,expires:Date.now()+600000});});
 app.post('/api/links',(q,r)=>{if(q.user.role!=='caregiver')return r.status(403).json({error:'Caregiver account required'});const code=z.string().length(16).parse(q.body.code);const invite=db.prepare('SELECT * FROM invites WHERE hash=? AND expires>?').get(sha(code),Date.now());if(!invite)return r.status(400).json({error:'Code invalid or expired'});db.prepare('INSERT OR IGNORE INTO links VALUES(?,?)').run(invite.patient,q.user.id);db.prepare('DELETE FROM invites WHERE hash=?').run(sha(code));audit(q.user.id,'link:accepted',invite.patient);r.json({ok:true});});
 app.post('/api/links/by-id',(q,r)=>{if(q.user.role!=='caregiver')return r.status(403).json({error:'Caregiver account required'});const patientId=z.uuid().parse(q.body.patientId);const patient=db.prepare("SELECT id FROM users WHERE id=? AND role='patient'").get(patientId);if(!patient)return r.status(404).json({error:'No patient found with that ID'});const settingsRow=db.prepare("SELECT payload FROM records WHERE patient=? AND kind='settings'").get(patientId);const shareOn=settingsRow&&JSON.parse(settingsRow.payload).shareViaId===true;if(!shareOn)return r.status(403).json({error:'This patient has not enabled connecting by Patient ID'});db.prepare('INSERT OR IGNORE INTO links VALUES(?,?)').run(patientId,q.user.id);audit(q.user.id,'link:accepted-by-id',patientId);r.json({ok:true});});
 app.delete('/api/links/:id',(q,r)=>{if(q.user.role==='patient')db.prepare('DELETE FROM links WHERE patient=? AND caregiver=?').run(q.user.id,q.params.id);else db.prepare('DELETE FROM links WHERE caregiver=? AND patient=?').run(q.user.id,q.params.id);audit(q.user.id,'link:revoked',q.params.id);r.json({ok:true});});
 app.get('/api/patients/:patient/records',access,(q,r)=>r.json(db.prepare('SELECT * FROM records WHERE patient=? ORDER BY updated').all(q.patient).map(x=>({id:x.id,kind:x.kind,data:JSON.parse(x.payload),updated:x.updated}))));
 app.post('/api/patients/:patient/events',access,(q,r)=>{const e=z.object({eventId:z.uuid(),id:z.string().min(1).max(100),kind:z.enum(Object.keys(schemas)),op:z.enum(['put','delete']),data:z.unknown().optional()}).parse(q.body);if(q.user.role==='caregiver'&&!['reminder','alert','family','place','journey','report','memory'].includes(e.kind))return r.status(403).json({error:'This action belongs to the patient'});
 if(db.prepare('SELECT 1 FROM receipts WHERE patient=? AND event_id=?').get(q.patient,e.eventId))return r.json({ok:true,duplicate:true});
 if(e.kind==='settings'&&(e.id!=='settings'||e.op==='delete'))return r.status(400).json({error:'Update the canonical settings record to withdraw consent'});if(e.kind==='location'&&e.id!=='latest-location')return r.status(400).json({error:'Only the latest location is stored'});
 const old=db.prepare('SELECT kind FROM records WHERE patient=? AND id=?').get(q.patient,e.id);if(old&&old.kind!==e.kind)return r.status(409).json({error:'Record kind mismatch'});
 const data=e.op==='put'?schemas[e.kind].parse(e.data):null;
 if(e.kind==='location'&&e.op==='put'){const settings=db.prepare("SELECT payload FROM records WHERE patient=? AND kind='settings'").get(q.patient);if(!settings||!JSON.parse(settings.payload).locationConsent)return r.status(403).json({error:'Location sharing consent required'});}
 db.exec('BEGIN');try{if(e.op==='delete')db.prepare('DELETE FROM records WHERE patient=? AND id=?').run(q.patient,e.id);else db.prepare('INSERT INTO records VALUES(?,?,?,?,?) ON CONFLICT(id,patient) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').run(e.id,q.patient,e.kind,JSON.stringify(data),Date.now());if(e.kind==='settings'&&data){audit(q.user.id,'consent:location:'+data.locationConsent,q.patient);if(!data.locationConsent)db.prepare("DELETE FROM records WHERE patient=? AND kind='location'").run(q.patient);}db.prepare('INSERT INTO receipts VALUES(?,?)').run(q.patient,e.eventId);audit(q.user.id,e.kind+':'+e.op,q.patient);db.exec('COMMIT');}catch(err){db.exec('ROLLBACK');throw err;}r.json({ok:true});});
 app.get('/api/export',(q,r)=>{const records=db.prepare('SELECT * FROM records WHERE patient=?').all(q.user.id);const logs=db.prepare('SELECT action,target,at FROM audit WHERE actor=?').all(q.user.id);r.json({user:publicUser(q.user),records,audit:logs});});
 app.delete('/api/account',(q,r)=>{if(q.body.confirm!=='DELETE')return r.status(400).json({error:'Confirmation required'});db.prepare('DELETE FROM audit WHERE actor=? OR target=?').run(q.user.id,q.user.id);db.prepare('DELETE FROM deliveries WHERE patient=?').run(q.user.id);db.prepare('DELETE FROM users WHERE id=?').run(q.user.id);r.clearCookie('smriti_session',{path:'/'});r.json({ok:true});});
 app.get('/api/weather',async(q,r)=>{if(!process.env.OPENWEATHER_API_KEY)return r.status(503).json({error:'Weather is not configured. No live weather available.'});const p=z.object({lat:z.coerce.number().min(-90).max(90),lng:z.coerce.number().min(-180).max(180)}).parse(q.query);const url=new URL('https://api.openweathermap.org/data/2.5/weather');Object.entries({lat:p.lat,lon:p.lng,appid:process.env.OPENWEATHER_API_KEY,units:'metric'}).forEach(([k,v])=>url.searchParams.set(k,v));const response=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Weather provider unavailable');const data=await response.json();r.json({temperature:data.main.temp,description:data.weather[0].description,at:Date.now()});});
 app.post('/api/transcribe',express.raw({type:['audio/*','application/octet-stream'],limit:'10mb'}),async(q,r)=>{if(!process.env.OPENAI_API_KEY)return r.status(503).json({error:'Whisper is not configured'});if(!Buffer.isBuffer(q.body))return r.status(400).json({error:'Audio required'});const form=new FormData();form.append('file',new Blob([q.body],{type:q.get('content-type')}),'recording.webm');form.append('model','whisper-1');const response=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENAI_API_KEY},body:form,signal:AbortSignal.timeout(60000)});if(!response.ok)throw new Error('Transcription provider unavailable');const data=await response.json();r.json({text:data.text});});
 app.post('/api/push-token',(q,r)=>{const token=z.string().min(10).max(4096).parse(q.body.token);db.prepare('INSERT OR REPLACE INTO push_tokens VALUES(?,?)').run(q.user.id,token);r.json({ok:true});});
 const assistantLimiter=rateLimit({windowMs:15*60000,limit:30,standardHeaders:'draft-7',legacyHeaders:false});
 app.post('/api/assistant',assistantLimiter,async(q,r)=>{
  if(!process.env.GROQ_API_KEY)return r.status(503).json({error:'The AI assistant is not configured yet. Ask the app admin to add a GROQ_API_KEY.'});
  const v=z.object({message:z.string().trim().min(1).max(1000),history:z.array(z.object({role:z.enum(['user','assistant']),content:z.string().max(2000)})).max(12).optional(),audience:z.enum(['patient','caregiver']).optional(),lang:z.string().max(10).optional(),context:z.object({stage:z.string().max(40).optional(),challenges:z.array(z.string().max(60)).max(10).optional()}).optional()}).parse(q.body);
  let system;
  if(v.audience==='patient'){
   system='You are a gentle, patient companion inside SmritiSaathi, an app for people living with dementia. You are talking directly to the patient, not a caregiver. Use very short sentences, simple everyday words, and a warm, reassuring, unhurried tone. Answer everyday questions (the day, time, weather, their reminders, family, or general friendly conversation) and encourage their memory games. Never give medical, medication, or diagnostic advice — if asked, gently suggest they ask their caregiver or doctor. If they seem confused, distressed, or unsafe, gently encourage them to tell their caregiver or use the "I need help" button in the app. Keep every reply under 60 words.';
   if(v.lang&&v.lang!=='en')system+=` Reply in the ${v.lang} language the patient is using, in simple script and words they will recognise.`;
  }else{
   system='You are the caregiver support assistant inside SmritiSaathi, a dementia-care app. Only answer questions about dementia and Alzheimer\'s caregiving: daily routines, communication techniques, safety at home, behaviour and mood changes, nutrition, sleep, medicine reminders, wandering, sundowning, and emotional support for the caregiver. Keep replies short (under 130 words), warm, practical, and in plain language. If the question is unrelated to dementia care, gently say you can only help with dementia-care questions here. You are not a doctor: for medical emergencies, sudden symptom changes, or medication decisions, always tell the caregiver to contact a qualified doctor promptly.';
   if(v.context&&(v.context.stage||v.context.challenges?.length)){
    system+=` Known context for this conversation — dementia stage: ${v.context.stage||'not specified'}; hardest current behaviours: ${(v.context.challenges||[]).join(', ')||'not specified'}. Quietly tailor every suggestion to this stage and these specific behaviours whenever it's relevant — don't repeat the context back to the caregiver each time.`;
   }
  }
  const messages=[{role:'system',content:system},...(v.history||[]),{role:'user',content:v.message}];
  const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+process.env.GROQ_API_KEY},body:JSON.stringify({model:'llama-3.3-70b-versatile',messages,max_tokens:350,temperature:0.4}),signal:AbortSignal.timeout(30000)});
  if(!response.ok)throw new Error('The assistant is unavailable right now. Please try again shortly.');
  const data=await response.json();
  const reply=data.choices?.[0]?.message?.content?.trim()||'Sorry, I could not find an answer just now. Please try rephrasing your question.';
  audit(q.user.id,'assistant:query',q.user.id);
  r.json({reply});
 });
 if(existsSync(resolve(root,'dist/index.html'))){app.use(express.static(resolve(root,'dist'),{setHeaders:(r,p)=>{if(p.endsWith('sw.js')||p.endsWith('index.html'))r.set('Cache-Control','no-cache');}}));app.get('/{*splat}',(_q,r)=>r.sendFile(resolve(root,'dist/index.html')));}
 app.use((err,_q,r,_n)=>{if(err instanceof z.ZodError)return r.status(400).json({error:'Please check the information you entered.',details:err.issues.map(x=>x.path.join('.')+': '+x.message)});console.error(err.message);r.status(500).json({error:'Unable to complete request'});});
 return {app,db};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const {app,db}=createApp();app.listen(process.env.PORT||3001,()=>console.log('SmritiSaathi API http://localhost:'+(process.env.PORT||3001)));if(process.env.GOOGLE_APPLICATION_CREDENTIALS){const {startPushWorker}=await import('./push.js');startPushWorker(db);}}
