import React,{useEffect,useRef,useState} from 'react';
import {translate as tr,tf} from './i18n';
import {readAloud} from './voice';
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const symbols=['🍎','🌼','🚌','🐟','🍵','🏠','🌳','⭐','☂️','🦋','🌙','🔑'];
export const domains={garden:'Memory',memory:'Memory',pattern:'Reasoning',sequence:'Working memory',routine:'Planning',family:'Personal memory',detail:'Attention',tune:'Auditory memory',arithmetic:'Reasoning',attention:'Attention'};
// All routine step labels come from i18n keys so they translate with the
// rest of the app instead of always showing English.
const ROUTINE_KEY_SETS=[['rWakeUp','rBrushTeeth','rEatBreakfast','rLeaveHome'],['rWashHands','rPrepareFood','rEatMeal','rWashDishes'],['rPutSocks','rPutShoes','rTieShoelaces','rGoWalk']];
function question(game,level,family,lang){
 const t=k=>tr(lang,k),f=(k,vars)=>tf(lang,k,vars);
 const n=2+level;
 if(game==='memory'){const target=pick(symbols);return {prompt:t('gMemoryPrompt'),study:target,question:t('gMemoryQuestion'),options:shuffle([target,...shuffle(symbols.filter(x=>x!==target)).slice(0,Math.min(n,5)-1)]),answer:target};}
 if(game==='pattern'){const step=level+1,start=Math.ceil(Math.random()*9);return {prompt:t('gPatternPrompt'),study:null,question:[0,1,2].map(i=>start+i*step).join('  ·  ')+'  ·  ?',options:shuffle([start+3*step,start+2*step+1,start+4*step,start+3*step-1].map(String).filter((v,i,a)=>a.indexOf(v)===i)),answer:String(start+3*step)};}
 if(game==='sequence'){const a=Array.from({length:n},()=>Math.floor(Math.random()*9)+1);return {prompt:t('gSequencePrompt'),study:a.join(' '),question:t('gSequenceQuestion'),answer:a.join(''),input:true};}
 if(game==='routine'){const keys=pick(ROUTINE_KEY_SETS);const a=keys.map(t);return {prompt:t('gRoutinePrompt'),question:t('gRoutineQuestion'),order:a,options:shuffle(a),answer:a.join('|')};}
 if(game==='family'){if(family.length<2)return null;const p=pick(family);return {prompt:t('gFamilyPrompt'),study:null,question:f('gFamilyQuestion',{relation:p.relation}),options:shuffle([...new Set([p.name,...family.filter(x=>x.name!==p.name).map(x=>x.name)])]),answer:p.name};}
 if(game==='detail'){const a=shuffle(symbols).slice(0,n);const target=pick(a);return {prompt:t('gDetailPrompt'),study:a.join(' '),question:t('gDetailQuestion'),options:shuffle([target,...shuffle(symbols.filter(x=>!a.includes(x))).slice(0,3)]),answer:target};}
 if(game==='tune'){const notes=Array.from({length:Math.min(n,5)},()=>pick([1,2,3]));return {prompt:t('gTunePrompt'),question:t('gTuneQuestion'),notes,options:['1','2','3'],answer:notes.join(''),input:true};}
 if(game==='arithmetic'){const a=Math.ceil(Math.random()*level*5),b=Math.ceil(Math.random()*5);return {prompt:t('gArithmeticPrompt'),question:f('gArithmeticQuestion',{a,b}),answer:String(a+b),input:true};}
 const target=pick(symbols),others=shuffle(symbols.filter(x=>x!==target)).slice(0,3);const count=Math.ceil(Math.random()*n);return {prompt:t('gAttentionPrompt'),question:f('gAttentionQuestion',{symbol:target}),display:shuffle([...Array(count).fill(target),...Array.from({length:n+2},()=>pick(others))]).join(' '),answer:String(count),input:true};
}
export default function Game({id,level,lang,family,onSave,onClose}){const t=k=>tr(lang,k);const [round,setRound]=useState(0),[q,setQ]=useState(()=>question(id,level,family,lang)),[study,setStudy]=useState(true),[input,setInput]=useState(''),[order,setOrder]=useState([]),[result,setResult]=useState(null),[results,setResults]=useState([]),[finished,setFinished]=useState(false),[error,setError]=useState('');const start=useRef(performance.now());const audio=useRef(null);const committed=useRef(false);
 useEffect(()=>{setStudy(true);start.current=performance.now();if(q?.study){const timer=setTimeout(()=>{setStudy(false);start.current=performance.now();},Math.max(2500,6500-level*500));return ()=>clearTimeout(timer);}setStudy(false);},[q,level]);
 useEffect(()=>()=>{audio.current?.close();window.speechSynthesis?.cancel();},[]);
 function playNotes(){try{const Audio=window.AudioContext||window.webkitAudioContext;audio.current?.close();const ctx=new Audio();audio.current=ctx;q.notes.forEach((n,i)=>{const o=ctx.createOscillator(),gain=ctx.createGain();o.frequency.value=[0,261.63,329.63,392][n];gain.gain.value=.13;o.connect(gain);gain.connect(ctx.destination);o.start(ctx.currentTime+i*.65);o.stop(ctx.currentTime+i*.65+.45);});start.current=performance.now();}catch{setError(t('audioUnavailable'));}}
 function answer(value){if(result!==null||study)return;const clean=x=>x.replace(/[\s,]/g,'').toLowerCase();const correct=clean(String(value))===clean(q.answer);const item={accuracy:correct?1:0,latency:performance.now()-start.current};setResults([...results,item]);setResult(correct);}
 async function next(){if(round===4){if(committed.current)return;committed.current=true;try{await onSave({game:id,accuracy:results.reduce((s,x)=>s+x.accuracy,0)/results.length,latency:Math.round(results.reduce((s,x)=>s+x.latency,0)/results.length),level,at:Date.now(),rounds:results.length});setFinished(true);}catch(e){committed.current=false;setError(e.message);}return;}setRound(round+1);setQ(question(id,level,family,lang));setResult(null);setInput('');setOrder([]);}
 if(!q)return <section className="card"><h2>{t('family')}</h2><p>{t('familyHelp')}</p><button onClick={onClose}>{t('back')}</button></section>;
 if(finished)return <section className="game card"><span className="eyebrow">{t('complete')}</span><h2>{t('thanksPractising')}</h2><div className="score-big">{results.filter(x=>x.accuracy).length} / 5</div><p>{t('activitySavedNote')}</p><button onClick={onClose}>{t('done')}</button></section>;
 return <section className="game card"><div className="row"><button className="quiet" onClick={onClose}>{t('back')}</button><span>{t('level')} {level} · {round+1} / 5</span></div><progress value={round} max="5"/><h2>{t(id)}</h2><p>{q.prompt}</p><button className="quiet" onClick={async()=>{try{await readAloud(q.prompt+'. '+q.question,lang);}catch(e){setError(e.message);}}}>{t('listen')}</button>{study?<div className="stimulus" aria-live="polite">{q.study}</div>:<><h3>{q.question}</h3>{q.display&&<div className="stimulus">{q.display}</div>}{q.notes&&<button onClick={playNotes}>{t('playNotesLabel')}</button>}{q.order?<><div className="choices">{q.options.map(x=><button disabled={order.includes(x)||result!==null} key={x} onClick={()=>{const a=[...order,x];setOrder(a);if(a.length===q.order.length)answer(a.join('|'));}}>{x}</button>)}</div><p>{order.join(' → ')}</p></>:q.input?<form onSubmit={e=>{e.preventDefault();answer(input);}}><label>{t('answer')}<input autoComplete="off" inputMode="numeric" value={input} onChange={e=>setInput(e.target.value)} disabled={result!==null}/></label><button disabled={!input||result!==null}>{t('submit')}</button></form>:<div className="choices">{q.options.map(x=><button key={x} disabled={result!==null} onClick={()=>answer(x)}>{x}</button>)}</div>}</>}{result!==null&&<div className="feedback" role="status"><strong>{result?t('correct'):t('incorrect')}</strong>{!result&&<p>{t('answerPrefix')}{q.answer.replaceAll('|',' → ')}</p>}<button onClick={next}>{round===4?t('done'):t('next')}</button></div>}{error&&<p role="alert">{error}</p>}</section>;
}
