export const TOTAL_LEVELS=1000;
export const SYMBOLS=['apple','cherry','grape','citrus','carrot','flower','leaf','tree','sun','moon','cloud','snow','umbrella','heart','star','gem','gift','music','bell','key','cup','book','bird','fish','shell','bug','kite','flame','sprout','cake','crown','clover'];
export const CHAPTERS=['First Light','Apple Orchard','Wildflower Walk','Tea Garden','Butterfly Trail','Rainy Afternoon','Golden Meadow','Moonlit Lake','Little Treasures','Quiet Grove','Coral Cove','Cloud Garden','Starlight Path','Festival Lights','Crystal Valley','Birdsong Woods','Autumn Lane','Sunrise Summit','Secret Garden','Memory Pavilion'];
function random(seed){let a=seed>>>0;return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
function shuffle(values,rng){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function levelConfig(level){if(!Number.isInteger(level)||level<1||level>TOTAL_LEVELS)throw new RangeError('Choose a level from 1 to 1000');const chapter=Math.floor((level-1)/50),pairs=Math.min(12,3+Math.floor((level-1)/100));const step=(level-1)%100;return {level,chapter,name:CHAPTERS[chapter],pairs,columns:pairs<=4?4:pairs<=8?4:6,target:pairs+Math.max(2,Math.ceil(pairs*(1.1-step/200))),previewMs:Math.max(1800,5200-Math.floor((level-1)/50)*150),theme:chapter%5};}
export function makeDeck(level){const cfg=levelConfig(level),rng=random(level*2654435761+871);const chosen=shuffle(SYMBOLS,rng).slice(0,cfg.pairs);return shuffle(chosen.flatMap(symbol=>[symbol,symbol]),rng).map((symbol,index)=>({symbol,index}));}
export function starsFor(level,moves,hints=0){const {target}=levelConfig(level);if(moves<=target&&hints===0)return 3;if(moves<=Math.ceil(target*1.5)&&hints<=2)return 2;return 1;}
export function campaignProgress(scores){const best={};for(const s of scores){if(s.game!=='garden'||!Number.isInteger(s.campaignLevel)||s.campaignLevel<1||s.campaignLevel>TOTAL_LEVELS)continue;const old=best[s.campaignLevel];if(!old||s.stars>old.stars||(s.stars===old.stars&&s.moves<old.moves))best[s.campaignLevel]=s;}let unlocked=1;while(unlocked<TOTAL_LEVELS&&best[unlocked])unlocked++;return {best,unlocked,completed:Object.keys(best).length,stars:Object.values(best).reduce((n,s)=>n+(s.stars||0),0)};}
export function newRun(level,attempt){levelConfig(level);return {version:1,level,attempt,phase:'ready',selected:[],matched:[],moves:0,hints:0,seconds:0,saved:false};}
export function restoreRun(value){if(!value||value.version!==1||typeof value.attempt!=='string')return null;try{const cfg=levelConfig(value.level);if(!['ready','preview','playing','paused','hint','won'].includes(value.phase)||!Number.isInteger(value.moves)||value.moves<0||!Number.isInteger(value.hints)||value.hints<0||!Number.isFinite(value.seconds)||value.seconds<0)return null;const deck=makeDeck(value.level);if(!Array.isArray(value.matched)||!Array.isArray(value.selected)||value.selected.length>2)return null;const matched=[...new Set(value.matched)];if(matched.some(x=>!SYMBOLS.includes(x)||!deck.some(c=>c.symbol===x)))return null;if(value.selected.some(i=>!Number.isInteger(i)||i<0||i>=cfg.pairs*2||matched.includes(deck[i].symbol)))return null;return {...value,matched,selected:[],phase:matched.length===cfg.pairs?'won':value.phase==='ready'?'ready':'paused'};}catch{return null;}}
export function gameReducer(state,action){const deck=makeDeck(state.level);switch(action.type){
 case 'start':return state.phase==='ready'?{...state,phase:'preview'}:state;
 case 'play':return ['preview','hint','paused'].includes(state.phase)?{...state,phase:'playing'}:state;
 case 'tick':return state.phase==='playing'?{...state,seconds:state.seconds+1}:state;
 case 'pause':return ['playing','preview','hint'].includes(state.phase)?{...state,phase:'paused',selected:[]}:state;
 case 'hint':return state.phase==='playing'&&!state.selected.length?{...state,phase:'hint',hints:state.hints+1}:state;
 case 'settle':return state.phase==='playing'&&state.selected.length===2?{...state,selected:[]}:state;
 case 'select':{const i=action.index;if(state.phase!=='playing'||state.selected.length===2||!Number.isInteger(i)||!deck[i]||state.selected.includes(i)||state.matched.includes(deck[i].symbol))return state;if(!state.selected.length)return {...state,selected:[i]};const first=state.selected[0],moves=state.moves+1;if(deck[first].symbol===deck[i].symbol){const matched=[...state.matched,deck[i].symbol];return {...state,moves,matched,selected:[],phase:matched.length===deck.length/2?'won':'playing'};}return {...state,moves,selected:[first,i]};}
 case 'saved':return {...state,saved:true};
 case 'load':return action.run;
 default:return state;
}}
