export const languages=[['en','English','en-IN'],['hi','हिन्दी','hi-IN'],['as','অসমীয়া','as-IN'],['kha','Khasi','kha-IN'],['lus','Mizo','lus-IN'],['mni','মণিপুরী','mni-IN'],['brx','बड़ो','brx-IN']];

// NOTE ON TRANSLATION COVERAGE:
// en, hi and as (Assamese) are fully translated for every key used in the app.
// kha (Khasi), lus (Mizo), mni (Manipuri/Meitei) and brx (Bodo) only have
// translations for short, common words/phrases. These are genuinely
// low-resource languages and getting longer sentences (safety notes, journey
// instructions, SOS text) wrong in an app used by memory-impaired patients
// is a real risk, so untranslated keys deliberately fall back to English
// (see `translate` below) instead of guessing. Add more entries to the kha/
// lus/mni/brx objects below (ideally reviewed by a native speaker) to expand
// coverage — the app will pick them up automatically, no other code changes
// needed.

const en={
  garden:'Memory Garden',home:'My day',games:'Mind games',reminders:'Reminders',journey:'Places & journeys',care:'Care circle',privacy:'Privacy & settings',profile:'Profile',music:'Music',stories:'Story time',
  hello:'A little practice. A brighter day.',welcome:'Welcome back',start:'Start activity',save:'Save',cancel:'Cancel',back:'Back',listen:'Read aloud',speak:'Speak',stop:'Stop',today:'Today',done:'Done',delete:'Delete',empty:'Nothing here yet',signout:'Sign out',name:'Name',email:'Email',password:'Password',patient:'Patient',caregiver:'Caregiver',signin:'Sign in',signup:'Create account',next:'Next',answer:'Your answer',submit:'Check answer',level:'Level',
  memory:'Memory pairs',pattern:'Pattern finder',sequence:'Number sequence',routine:'Daily routine',family:'Familiar people',detail:'Notice the detail',tune:'Melody memory',arithmetic:'Everyday numbers',attention:'Focus & find',
  support:'Cognitive support and screening assistance. Not a diagnosis.',offline:'Offline · saved on this device',online:'Connected',practice:'Practice at your own pace. You can stop whenever you like.',complete:'Activity complete',correct:'That is right!',incorrect:'Good try. Let’s keep going.',pending:'Waiting to sync',
  consent:'I agree to store my account and activity data for cognitive support. I understand this is not a diagnostic service.',sharing:'Share my activity, reminders, saved places and consented location with the caregiver who receives this code.',locationConsent:'Allow my location to be stored and shared with linked caregivers while tracking is on.',translation:'Regional translations are a draft. Some instructions use English; native-speaker review is needed.',sos:'Get help',overview:'Care overview',
  journeyTitle:'Journey',journeyLead:'Choose where you want to go, check the route, then start live guidance.',searchDestination:'Search destination',searchPlaceholder:'Search AIIMS, hospital, Home, market…',search:'Search',planJourney:'Plan your journey',planJourneyDesc:'Search for a destination above. The map, source, destination and estimated travel time will appear here.',sourceLabel:'SOURCE',destinationLabel:'DESTINATION',yourCurrentLocation:'Your current location',locationNotShared:'Location not shared',estimatedTime:'Estimated time',calculating:'Calculating…',startLiveJourney:'Start live journey',preparingRoute:'Preparing route…',journeyHelper:'After you start, the app will open live navigation. Your location marker will move with GPS, the current turn will be highlighted, and voice guidance will announce instructions such as “turn right” or “turn left”.',journeyCompleteHeading:'Journey complete',startAnother:'Start another journey',yourLocation:'Your location',noLocationShared:'No location shared yet.',locationSharingOff:'Location sharing is off',locationSharingOffDesc:'Turn on “Share my location” in Privacy & settings before starting live location.',openPrivacySettings:'Open Privacy & settings',startLiveLocation:'Start live location',stopLiveLocation:'Stop live location',safetyNote:'Safety note',safetyNoteDesc:'Location sharing is permission-based. During a live journey, moving significantly away from the planned route sends the linked caregiver an alert with the patient’s current location.',voiceLabel:'Voice',backToJourney:'← Back to journey',liveJourneyBadge:'LIVE JOURNEY',demoRoutePreview:'Demo route preview',followingLiveGps:'Following your live GPS location',demoMarkerMoving:'Demo marker moving on route',liveGpsTrackingActive:'Live GPS tracking active',liveLocationActive:'Live location active',now:'NOW',routeAlertLabel:'ROUTE ALERT',followHighlightedRoute:'Follow the highlighted route',offRouteTitle:'You are off the planned route',offRouteDesc:'Caregiver has been alerted. Move back toward the blue route.',endLiveJourney:'End live journey',currentPlace:'Current place',fetchingAddress:'Finding your address…',noAddress:'Address unavailable',statusIdle:'Ready for a familiar journey',statusOn:'Live journey active',statusOff:'Off planned route — caregiver alerted',statusTurn:'Turn-by-turn guidance active',statusDone:'Journey complete',patientLiveLabel:'Patient — live location',patientCurrentLabel:'Patient — current location',destinationTooltip:'Destination',
  gMemoryPrompt:'Remember this symbol',gMemoryQuestion:'Which symbol did you see?',gPatternPrompt:'What number comes next?',gSequencePrompt:'Remember the numbers in order',gSequenceQuestion:'Type the numbers in the same order',gRoutinePrompt:'Put this example routine in order',gRoutineQuestion:'Tap the steps from first to last. Your own routine may be different.',gFamilyPrompt:'Think of someone familiar',gFamilyQuestion:'Who is your {relation}?',gDetailPrompt:'Look carefully at these symbols',gDetailQuestion:'Which symbol was there?',gTunePrompt:'Listen to the notes: 1 low, 2 middle, 3 high',gTuneQuestion:'Tap the same notes in order',gArithmeticPrompt:'Everyday numbers',gArithmeticQuestion:'You have {a} cups and add {b} more. How many cups?',gAttentionPrompt:'Find the matching symbols',gAttentionQuestion:'How many {symbol} symbols can you see?',
  rWakeUp:'Wake up',rBrushTeeth:'Brush teeth',rEatBreakfast:'Eat breakfast',rLeaveHome:'Leave home',rWashHands:'Wash hands',rPrepareFood:'Prepare food',rEatMeal:'Eat the meal',rWashDishes:'Wash dishes',rPutSocks:'Put on socks',rPutShoes:'Put on shoes',rTieShoelaces:'Tie shoelaces',rGoWalk:'Go for a walk',
  answerPrefix:'Answer: ',reminderPrefix:'Reminder: ',onDatePrefix:'On ',streakProgress:'You have a {streak} day streak and completed {count} activities',unlockedLabel:'Unlocked',keepPractisingLabel:'Keep practising',hearProgress:'Hear my progress',
  familyHelp:'Add at least two familiar names and distinct relationships in Care circle first. Only use details the patient agrees to store.',thanksPractising:'Thank you for practising',activitySavedNote:'Your activity has been saved. This score is not a medical assessment.',audioUnavailable:'Audio is unavailable. Choose another activity.',playNotesLabel:'▶ Play notes',
  yourSpace:'YOUR SPACE',editProfileTitle:'Edit Profile',profileLead:'Make SmritiSaathi feel familiar and personal.',tabAccount:'Account',tabReports:'Medical History',tabRewards:'Rewards',uploadPhoto:'Upload photo',removeLabel:'Remove',fullName:'Full name',ageLabel:'Age',phoneLabel:'Phone',saveChanges:'Save changes',personalHelpVoice:'PERSONAL HELP VOICE',addYourVoice:'Add your voice',voiceNoteDesc:'Record a short familiar voice note. If the patient goes off-route during a live journey, this saved voice is attached to the caregiver help alert.',stopRecording:'Stop recording',savingEllipsis:'Saving…',recordAgain:'Record again',removeVoiceLabel:'Remove voice',recordingHint:'Recording… speak naturally. It will stop automatically after 5 seconds.',yourRecords:'YOUR RECORDS',medicalHistoryTitle:'Medical History',rewardsStreakTitle:'Rewards & Streak',currentStreak:'Current day streak',activitiesCompleted:'Activities completed',practiceAccuracy:'Practice accuracy',badgeFirst:'First step',badgeFive:'5 activities',badgeTen:'10 activities',badgeStreak:'3-day streak',
  voiceUnsupported:'Voice recording is not supported in this browser.',voiceRecordFailed:'Voice recording failed. Please try again.',micPermissionNeeded:'Microphone permission is required.',voiceTooLong:'Please record a shorter voice note (up to 5 seconds).',voiceSaveFailed:'Could not save your voice.',
  tabHome:'My Home',myHomeTitle:'My Home',myHomeDesc:'Set your home address. Its location will be shown on a map below.',homeAddressLabel:'Home address',homeAddressPlaceholder:'Search your home address…',saveHomeAddress:'Save as my home',updateHomeAddress:'Update address',removeHomeAddress:'Remove home',myHomeAlertNote:'While live location is turned on (in Journey), your caregiver will get an alert if you move away from this home area.',nearHomeCue:'You are near home.',
  storyEyebrow:'MY STORY TIME',storyChooseState:'Choose a state',storyChooseStateLead:'Pick one of the 8 North-East sister states and read or listen to its folk tales.',storyBackToStates:'All states',storyStateSub:'{icon} · {count} stories',storyStoriesOf:'Stories of {state}',storyStorySub:'{count} questions · folk tale',storyBackToStories:'{state} stories',storyLangLabel:'Reading / listening language',storyChapterLead:'This story is told in {count} short chapters. Read or listen to them one at a time.',storyChapter:'Chapter {n}',storyBackToChapters:'All chapters',storyPrevChapter:'Previous chapter',storyNextChapter:'Next chapter',storyStartQuestions:'Start the questions',storyListenChapter:'Listen to chapter',storyPlaying:'Playing…',storyQuestionLabel:'QUESTION {n}',storyYourAnswer:'Your answer',storyAnswerPlaceholder:'Type your answer, or use the mic',storySubmit:'Submit',storyHintPrefix:'Hint: ',storyGoodFeedback:'Well done! You remembered that correctly.',storyTryFeedback:'No worries, good try! The correct answer was: {answer}.',storyDoneHeading:'Well done!',storyDoneBody:'You finished reading/listening to "{title}" and answered {count} questions.',storyAnotherStory:'Another story from {state}'
};

const hi={
  garden:'यादों का बगीचा',home:'मेरा दिन',games:'दिमागी खेल',reminders:'याद दिलाना',journey:'जगह और यात्रा',care:'देखभाल साथी',privacy:'गोपनीयता और सेटिंग',profile:'प्रोफ़ाइल',music:'संगीत',stories:'कहानी का समय',
  hello:'थोड़ा अभ्यास। बेहतर दिन।',welcome:'आपका स्वागत है',start:'खेल शुरू करें',save:'सहेजें',cancel:'रद्द करें',back:'वापस',listen:'सुनें',speak:'बोलें',stop:'रोकें',today:'आज',done:'पूरा हुआ',delete:'हटाएँ',empty:'अभी कुछ नहीं है',signout:'साइन आउट',name:'नाम',email:'ईमेल',password:'पासवर्ड',patient:'मरीज़',caregiver:'देखभालकर्ता',signin:'साइन इन',signup:'खाता बनाएँ',next:'अगला',answer:'आपका उत्तर',submit:'उत्तर जाँचें',level:'स्तर',
  memory:'याददाश्त के जोड़े',pattern:'पैटर्न खोजें',sequence:'संख्या क्रम',routine:'दैनिक दिनचर्या',family:'परिचित लोग',detail:'ध्यान से देखें',tune:'धुन याद करें',arithmetic:'रोज़मर्रा की गिनती',attention:'ध्यान लगाएँ',
  support:'याददाश्त में सहायता और शुरुआती जाँच में सहयोग। यह निदान नहीं है।',offline:'ऑफ़लाइन · इस उपकरण पर सहेजा गया',online:'जुड़ा हुआ',practice:'अपनी गति से अभ्यास करें। आप कभी भी रुक सकते हैं।',complete:'अभ्यास पूरा हुआ',correct:'सही जवाब!',incorrect:'अच्छा प्रयास। आगे बढ़ें।',pending:'सिंक होने का इंतज़ार',
  consent:'मैं याददाश्त सहायता के लिए अपने खाते और गतिविधि का डेटा सहेजने के लिए सहमत हूँ। मैं समझता/समझती हूँ कि यह कोई निदान सेवा नहीं है।',sharing:'जिस देखभालकर्ता को यह कोड मिले, उसके साथ मेरी गतिविधि, याद दिलाना, सहेजी गई जगहें और सहमति वाला स्थान साझा करें।',locationConsent:'ट्रैकिंग चालू रहते समय मेरा स्थान सहेजने और जुड़े हुए देखभालकर्ताओं के साथ साझा करने की अनुमति दें।',translation:'क्षेत्रीय अनुवाद अभी मसौदा हैं। कुछ निर्देश अंग्रेज़ी में हैं; मातृभाषी समीक्षा ज़रूरी है।',sos:'मदद लें',overview:'देखभाल का विवरण',
  journeyTitle:'यात्रा',journeyLead:'जहाँ जाना है वहाँ चुनें, रास्ता देखें, फिर लाइव मार्गदर्शन शुरू करें।',searchDestination:'गंतव्य खोजें',searchPlaceholder:'AIIMS, अस्पताल, घर, बाज़ार खोजें…',search:'खोजें',planJourney:'अपनी यात्रा की योजना बनाएँ',planJourneyDesc:'ऊपर गंतव्य खोजें। यहाँ नक्शा, स्रोत, गंतव्य और अनुमानित समय दिखेगा।',sourceLabel:'स्रोत',destinationLabel:'गंतव्य',yourCurrentLocation:'आपकी वर्तमान स्थिति',locationNotShared:'स्थान साझा नहीं किया गया',estimatedTime:'अनुमानित समय',calculating:'गणना हो रही है…',startLiveJourney:'लाइव यात्रा शुरू करें',preparingRoute:'रास्ता तैयार हो रहा है…',journeyHelper:'शुरू करने के बाद, ऐप लाइव नेविगेशन खोलेगा। आपका स्थान चिह्न GPS के साथ चलेगा, मौजूदा मोड़ हाइलाइट होगा, और आवाज़ मार्गदर्शन “दाएँ मुड़ें” या “बाएँ मुड़ें” जैसे निर्देश बोलेगा।',journeyCompleteHeading:'यात्रा पूरी हुई',startAnother:'एक और यात्रा शुरू करें',yourLocation:'आपकी स्थिति',noLocationShared:'अभी तक कोई स्थान साझा नहीं किया गया।',locationSharingOff:'स्थान साझा करना बंद है',locationSharingOffDesc:'लाइव स्थान शुरू करने से पहले गोपनीयता और सेटिंग में “मेरा स्थान साझा करें” चालू करें।',openPrivacySettings:'गोपनीयता और सेटिंग खोलें',startLiveLocation:'लाइव स्थान शुरू करें',stopLiveLocation:'लाइव स्थान रोकें',safetyNote:'सुरक्षा सूचना',safetyNoteDesc:'स्थान साझा करना अनुमति पर आधारित है। लाइव यात्रा के दौरान, तय रास्ते से काफी दूर जाने पर जुड़े देखभालकर्ता को मरीज़ के वर्तमान स्थान के साथ अलर्ट भेजा जाता है।',voiceLabel:'आवाज़',backToJourney:'← यात्रा पर वापस',liveJourneyBadge:'लाइव यात्रा',demoRoutePreview:'डेमो रास्ता पूर्वावलोकन',followingLiveGps:'आपकी लाइव GPS स्थिति का अनुसरण हो रहा है',demoMarkerMoving:'डेमो चिह्न रास्ते पर चल रहा है',liveGpsTrackingActive:'लाइव GPS ट्रैकिंग सक्रिय',liveLocationActive:'लाइव स्थान सक्रिय',now:'अभी',routeAlertLabel:'रास्ता चेतावनी',followHighlightedRoute:'हाइलाइट किए गए रास्ते का पालन करें',offRouteTitle:'आप तय रास्ते से हट गए हैं',offRouteDesc:'देखभालकर्ता को सूचित कर दिया गया है। नीले रास्ते की ओर वापस जाएँ।',endLiveJourney:'लाइव यात्रा समाप्त करें',currentPlace:'वर्तमान स्थान',fetchingAddress:'आपका पता खोजा जा रहा है…',noAddress:'पता उपलब्ध नहीं है',statusIdle:'एक परिचित यात्रा के लिए तैयार',statusOn:'लाइव यात्रा सक्रिय',statusOff:'तय रास्ते से हट गए — देखभालकर्ता को सूचित किया गया',statusTurn:'मोड़-दर-मोड़ मार्गदर्शन सक्रिय',statusDone:'यात्रा पूरी हुई',patientLiveLabel:'मरीज़ — लाइव स्थान',patientCurrentLabel:'मरीज़ — वर्तमान स्थान',destinationTooltip:'गंतव्य',
  gMemoryPrompt:'इस चिन्ह को याद रखें',gMemoryQuestion:'आपने कौन-सा चिन्ह देखा था?',gPatternPrompt:'अगली संख्या क्या है?',gSequencePrompt:'संख्याओं को क्रम में याद रखें',gSequenceQuestion:'संख्याओं को उसी क्रम में टाइप करें',gRoutinePrompt:'इस उदाहरण दिनचर्या को क्रम में लगाएँ',gRoutineQuestion:'पहले से आखिर तक चरणों पर टैप करें। आपकी अपनी दिनचर्या अलग हो सकती है।',gFamilyPrompt:'किसी जान-पहचान वाले के बारे में सोचें',gFamilyQuestion:'आपका {relation} कौन है?',gDetailPrompt:'इन चिन्हों को ध्यान से देखें',gDetailQuestion:'कौन-सा चिन्ह वहाँ था?',gTunePrompt:'सुर सुनें: 1 धीमा, 2 मध्यम, 3 ऊँचा',gTuneQuestion:'उसी क्रम में सुरों पर टैप करें',gArithmeticPrompt:'रोज़मर्रा की गिनती',gArithmeticQuestion:'आपके पास {a} कप हैं और {b} और मिलाए। कुल कितने कप हुए?',gAttentionPrompt:'मिलते हुए चिन्ह ढूँढें',gAttentionQuestion:'आप कितने {symbol} चिन्ह देख सकते हैं?',
  rWakeUp:'उठें',rBrushTeeth:'दाँत साफ़ करें',rEatBreakfast:'नाश्ता करें',rLeaveHome:'घर से निकलें',rWashHands:'हाथ धोएँ',rPrepareFood:'खाना बनाएँ',rEatMeal:'खाना खाएँ',rWashDishes:'बर्तन धोएँ',rPutSocks:'मोज़े पहनें',rPutShoes:'जूते पहनें',rTieShoelaces:'जूतों के फीते बाँधें',rGoWalk:'टहलने जाएँ',
  answerPrefix:'उत्तर: ',reminderPrefix:'याद दिलाना: ',onDatePrefix:'तारीख़: ',streakProgress:'आपने {streak} दिन लगातार अभ्यास किया है और {count} गतिविधियाँ पूरी की हैं',unlockedLabel:'खुल गया',keepPractisingLabel:'अभ्यास जारी रखें',hearProgress:'मेरी प्रगति सुनें',
  familyHelp:'पहले देखभाल साथी में कम से कम दो जान-पहचान वाले नाम और अलग-अलग रिश्ते जोड़ें। केवल वही जानकारी उपयोग करें जिसे सहेजने के लिए मरीज़ सहमत हो।',thanksPractising:'अभ्यास करने के लिए धन्यवाद',activitySavedNote:'आपकी गतिविधि सहेज ली गई है। यह अंक कोई चिकित्सीय आकलन नहीं है।',audioUnavailable:'ऑडियो उपलब्ध नहीं है। कोई और गतिविधि चुनें।',playNotesLabel:'▶ धुन सुनें',
  yourSpace:'आपकी जगह',editProfileTitle:'प्रोफ़ाइल संपादित करें',profileLead:'SmritiSaathi को अपने जैसा और अपनापन भरा बनाएँ।',tabAccount:'खाता',tabReports:'चिकित्सा इतिहास',tabRewards:'पुरस्कार',uploadPhoto:'फ़ोटो अपलोड करें',removeLabel:'हटाएँ',fullName:'पूरा नाम',ageLabel:'उम्र',phoneLabel:'फ़ोन',saveChanges:'बदलाव सहेजें',personalHelpVoice:'निजी सहायता आवाज़',addYourVoice:'अपनी आवाज़ जोड़ें',voiceNoteDesc:'एक छोटा, जाना-पहचाना आवाज़ संदेश रिकॉर्ड करें। यदि लाइव यात्रा के दौरान मरीज़ रास्ते से भटक जाए, तो यह सहेजी गई आवाज़ देखभालकर्ता की मदद वाली चेतावनी के साथ भेजी जाती है।',stopRecording:'रिकॉर्डिंग रोकें',savingEllipsis:'सहेज रहे हैं…',recordAgain:'फिर से रिकॉर्ड करें',removeVoiceLabel:'आवाज़ हटाएँ',recordingHint:'रिकॉर्डिंग हो रही है… सामान्य रूप से बोलें। यह 5 सेकंड बाद अपने आप रुक जाएगी।',yourRecords:'आपके रिकॉर्ड',medicalHistoryTitle:'चिकित्सा इतिहास',rewardsStreakTitle:'पुरस्कार और लगातार अभ्यास',currentStreak:'लगातार अभ्यास के दिन',activitiesCompleted:'पूरी की गई गतिविधियाँ',practiceAccuracy:'अभ्यास सटीकता',badgeFirst:'पहला कदम',badgeFive:'5 गतिविधियाँ',badgeTen:'10 गतिविधियाँ',badgeStreak:'3 दिन लगातार',
  voiceUnsupported:'इस ब्राउज़र में आवाज़ रिकॉर्डिंग समर्थित नहीं है।',voiceRecordFailed:'आवाज़ रिकॉर्ड नहीं हो पाई। कृपया फिर कोशिश करें।',micPermissionNeeded:'माइक्रोफ़ोन की अनुमति चाहिए।',voiceTooLong:'कृपया छोटा आवाज़ संदेश रिकॉर्ड करें (अधिकतम 5 सेकंड)।',voiceSaveFailed:'आपकी आवाज़ सहेजी नहीं जा सकी।',
  tabHome:'मेरा घर',myHomeTitle:'मेरा घर',myHomeDesc:'अपना घर का पता सेट करें। इसकी जगह नीचे नक्शे पर दिखेगी।',homeAddressLabel:'घर का पता',homeAddressPlaceholder:'अपने घर का पता खोजें…',saveHomeAddress:'मेरे घर के रूप में सहेजें',updateHomeAddress:'पता बदलें',removeHomeAddress:'घर हटाएँ',myHomeAlertNote:'जब लाइव स्थान चालू हो (यात्रा में), तो अगर आप इस घर के क्षेत्र से बाहर जाते हैं, तो आपके देखभालकर्ता को अलर्ट मिलेगा।',nearHomeCue:'आप घर के पास हैं।',
  storyEyebrow:'मेरी कहानी का समय',storyChooseState:'एक राज्य चुनें',storyChooseStateLead:'North-East की 8 सिस्टर स्टेट्स में से कोई एक राज्य चुनें और उसकी लोक-कथाएँ पढ़ें या सुनें।',storyBackToStates:'सभी राज्य',storyStateSub:'{icon} · {count} कहानियाँ',storyStoriesOf:'{state} की कहानियाँ',storyStorySub:'{count} सवाल · लोक-कथा',storyBackToStories:'{state} की कहानियाँ',storyLangLabel:'पढ़ने / सुनने की भाषा',storyChapterLead:'यह कहानी {count} छोटे अध्यायों में बाँटी गई है। एक-एक करके पढ़ें या सुनें।',storyChapter:'अध्याय {n}',storyBackToChapters:'सभी अध्याय',storyPrevChapter:'पिछला अध्याय',storyNextChapter:'अगला अध्याय',storyStartQuestions:'सवाल शुरू करें',storyListenChapter:'अध्याय सुनें',storyPlaying:'सुनाया जा रहा है…',storyQuestionLabel:'सवाल {n}',storyYourAnswer:'आपका जवाब',storyAnswerPlaceholder:'अपना जवाब टाइप करें, या माइक का उपयोग करें',storySubmit:'जमा करें',storyHintPrefix:'संकेत: ',storyGoodFeedback:'बहुत बढ़िया! आपको सही याद है।',storyTryFeedback:'कोई बात नहीं, अच्छी कोशिश थी! सही जवाब था: {answer}।',storyDoneHeading:'शाबाश!',storyDoneBody:'आपने "{title}" पूरी पढ़ी/सुनी और {count} सवालों के जवाब दिए।',storyAnotherStory:'{state} की एक और कहानी'
};

const as={
  garden:'সোঁৱৰণৰ বাগান',home:'মোৰ দিন',games:'মগজুৰ খেল',reminders:'সোঁৱৰাই দিয়া',journey:'ঠাই আৰু যাত্ৰা',care:'যত্নৰ সংগী',privacy:'গোপনীয়তা আৰু ছেটিংছ',profile:'প্ৰ’ফাইল',music:'সংগীত',stories:'কাহিনীৰ সময়',
  hello:'অলপ অনুশীলন। এটা উজ্জ্বল দিন।',welcome:'পুনৰ স্বাগতম',start:'কাৰ্যকলাপ আৰম্ভ কৰক',save:'সংৰক্ষণ কৰক',cancel:'বাতিল কৰক',back:'উভতি যাওক',listen:'শুনক',speak:'কওক',stop:'ৰখাওক',today:'আজি',done:'হ\'ল',delete:'মচক',empty:'ইয়াত এতিয়াও একো নাই',signout:'ছাইন আউট',name:'নাম',email:'ইমেইল',password:'পাছৱৰ্ড',patient:'ৰোগী',caregiver:'যত্নকাৰী',signin:'ছাইন ইন',signup:'একাউণ্ট বনাওক',next:'পৰৱৰ্তী',answer:'আপোনাৰ উত্তৰ',submit:'উত্তৰ পৰীক্ষা কৰক',level:'স্তৰ',
  memory:'সোঁৱৰণৰ যোৰ',pattern:'আৰ্হি বিচাৰক',sequence:'সংখ্যাৰ ক্ৰম',routine:'দৈনিক নিয়ম',family:'চিনাকি মানুহ',detail:'সূক্ষ্ম কথাত মন দিয়ক',tune:'সুৰ মনত ৰাখক',arithmetic:'দৈনন্দিন গণনা',attention:'মনোযোগ আৰু বিচাৰক',
  support:'স্মৃতিশক্তি সহায় আৰু প্ৰাথমিক পৰীক্ষাৰ সহযোগিতা। এইটো ৰোগ নিৰ্ণয় নহয়।',offline:'অফলাইন · এই ডিভাইচত সংৰক্ষিত',online:'সংযুক্ত',practice:'নিজৰ গতিত অনুশীলন কৰক। যেতিয়াই ইচ্ছা ৰখাব পাৰে।',complete:'কাৰ্যকলাপ সম্পূৰ্ণ',correct:'শুদ্ধ!',incorrect:'ভাল চেষ্টা। আকৌ চেষ্টা কৰক।',pending:'ছিংক হবলৈ অপেক্ষা কৰি আছে',
  consent:'মই স্মৃতিশক্তি সহায়ৰ বাবে মোৰ একাউণ্ট আৰু কাৰ্যকলাপৰ তথ্য সংৰক্ষণ কৰাত সন্মত হৈছোঁ। মই বুজি পাইছোঁ যে এইটো ৰোগ নিৰ্ণয় সেৱা নহয়।',sharing:'এই ক\'ড পোৱা যত্নকাৰীৰ সৈতে মোৰ কাৰ্যকলাপ, সোঁৱৰাই দিয়া, সংৰক্ষিত ঠাই আৰু সন্মতি দিয়া অৱস্থান শ্বেয়াৰ কৰক।',locationConsent:'ট্ৰেকিং অন থাকিলে মোৰ অৱস্থান সংৰক্ষণ আৰু সংযুক্ত যত্নকাৰীৰ সৈতে শ্বেয়াৰ কৰাৰ অনুমতি দিয়ক।',translation:'আঞ্চলিক অনুবাদ এতিয়াও খচৰা। কিছুমান নিৰ্দেশনা ইংৰাজীত আছে; মাতৃভাষী পৰ্যালোচনাৰ প্ৰয়োজন।',sos:'সহায় লওক',overview:'যত্নৰ বিৱৰণ',
  journeyTitle:'যাত্ৰা',journeyLead:'ক\'ত যাব বিচাৰে বাছক, পথ চাওক, তাৰ পিছত লাইভ পথনিৰ্দেশনা আৰম্ভ কৰক।',searchDestination:'গন্তব্য বিচাৰক',searchPlaceholder:'AIIMS, চিকিৎসালয়, ঘৰ, বজাৰ বিচাৰক…',search:'বিচাৰক',planJourney:'আপোনাৰ যাত্ৰাৰ পৰিকল্পনা কৰক',planJourneyDesc:'ওপৰত গন্তব্য বিচাৰক। মেপ, উৎস, গন্তব্য আৰু আনুমানিক সময় ইয়াত দেখা যাব।',sourceLabel:'উৎস',destinationLabel:'গন্তব্য',yourCurrentLocation:'আপোনাৰ বৰ্তমান অৱস্থান',locationNotShared:'অৱস্থান শ্বেয়াৰ কৰা হোৱা নাই',estimatedTime:'আনুমানিক সময়',calculating:'গণনা কৰি থকা হৈছে…',startLiveJourney:'লাইভ যাত্ৰা আৰম্ভ কৰক',preparingRoute:'পথ প্ৰস্তুত হৈ আছে…',journeyHelper:'আৰম্ভ কৰাৰ পিছত, এপটোৱে লাইভ নেভিগেষন খুলিব। আপোনাৰ অৱস্থানৰ চিহ্নটো GPS ৰ সৈতে চলিব, বৰ্তমানৰ মোৰটো হাইলাইট কৰা হ\'ব, আৰু কণ্ঠধ্বনিয়ে “সোঁফালে মুৰি যাওক” বা “বাওঁফালে মুৰি যাওক”ৰ দৰে নিৰ্দেশনা দিব।',journeyCompleteHeading:'যাত্ৰা সম্পূৰ্ণ হ\'ল',startAnother:'আৰু এটা যাত্ৰা আৰম্ভ কৰক',yourLocation:'আপোনাৰ অৱস্থান',noLocationShared:'এতিয়ালৈকে কোনো অৱস্থান শ্বেয়াৰ কৰা হোৱা নাই।',locationSharingOff:'অৱস্থান শ্বেয়াৰিং বন্ধ আছে',locationSharingOffDesc:'লাইভ অৱস্থান আৰম্ভ কৰাৰ আগতে গোপনীয়তা আৰু ছেটিংছত “মোৰ অৱস্থান শ্বেয়াৰ কৰক” অন কৰক।',openPrivacySettings:'গোপনীয়তা আৰু ছেটিংছ খোলক',startLiveLocation:'লাইভ অৱস্থান আৰম্ভ কৰক',stopLiveLocation:'লাইভ অৱস্থান বন্ধ কৰক',safetyNote:'সুৰক্ষা টোকা',safetyNoteDesc:'অৱস্থান শ্বেয়াৰিং অনুমতিৰ ওপৰত নিৰ্ভৰশীল। লাইভ যাত্ৰাৰ সময়ত, নিৰ্ধাৰিত পথৰ পৰা যথেষ্ট আঁতৰি গ\'লে সংযুক্ত যত্নকাৰীলৈ ৰোগীৰ বৰ্তমান অৱস্থানৰ সৈতে এলাৰ্ট পঠোৱা হয়।',voiceLabel:'কণ্ঠধ্বনি',backToJourney:'← যাত্ৰালৈ উভতি যাওক',liveJourneyBadge:'লাইভ যাত্ৰা',demoRoutePreview:'ডেমো পথ পূৰ্বদৰ্শন',followingLiveGps:'আপোনাৰ লাইভ GPS অৱস্থান অনুসৰণ কৰি আছে',demoMarkerMoving:'ডেমো চিহ্ন পথত চলি আছে',liveGpsTrackingActive:'লাইভ GPS ট্ৰেকিং সক্ৰিয়',liveLocationActive:'লাইভ অৱস্থান সক্ৰিয়',now:'এতিয়া',routeAlertLabel:'পথ সতৰ্কবাণী',followHighlightedRoute:'হাইলাইট কৰা পথ অনুসৰণ কৰক',offRouteTitle:'আপুনি নিৰ্ধাৰিত পথৰ পৰা আঁতৰি গৈছে',offRouteDesc:'যত্নকাৰীক জনোৱা হৈছে। নীলা পথৰ ফালে উভতি যাওক।',endLiveJourney:'লাইভ যাত্ৰা শেষ কৰক',currentPlace:'বৰ্তমান স্থান',fetchingAddress:'আপোনাৰ ঠিকনা বিচাৰি থকা হৈছে…',noAddress:'ঠিকনা উপলব্ধ নাই',statusIdle:'এটা চিনাকি যাত্ৰাৰ বাবে সাজু',statusOn:'লাইভ যাত্ৰা সক্ৰিয়',statusOff:'নিৰ্ধাৰিত পথৰ পৰা আঁতৰি গৈছে — যত্নকাৰীক জনোৱা হৈছে',statusTurn:'মোৰ-দ্বাৰা-মোৰ পথনিৰ্দেশনা সক্ৰিয়',statusDone:'যাত্ৰা সম্পূৰ্ণ হ\'ল',patientLiveLabel:'ৰোগী — লাইভ অৱস্থান',patientCurrentLabel:'ৰোগী — বৰ্তমান অৱস্থান',destinationTooltip:'গন্তব্য',
  gMemoryPrompt:'এই চিহ্নটো মনত ৰাখক',gMemoryQuestion:'আপুনি কোনটো চিহ্ন দেখিছিল?',gPatternPrompt:'পৰৱৰ্তী সংখ্যাটো কি?',gSequencePrompt:'সংখ্যাবোৰ ক্ৰমত মনত ৰাখক',gSequenceQuestion:'একেই ক্ৰমত সংখ্যাবোৰ টাইপ কৰক',gRoutinePrompt:'এই উদাহৰণ নিয়মটো ক্ৰমত সজাওক',gRoutineQuestion:'প্ৰথমৰ পৰা শেষলৈকে খাপবোৰত টিপক। আপোনাৰ নিজৰ নিয়ম বেলেগ হ\'ব পাৰে।',gFamilyPrompt:'কোনো চিনাকি মানুহৰ কথা ভাবক',gFamilyQuestion:'আপোনাৰ {relation} কোন?',gDetailPrompt:'এই চিহ্নবোৰ মন দি চাওক',gDetailQuestion:'কোনটো চিহ্ন তাত আছিল?',gTunePrompt:'সুৰবোৰ শুনক: ১ কম, ২ মধ্যম, ৩ উচ্চ',gTuneQuestion:'একেই ক্ৰমত সুৰবোৰত টিপক',gArithmeticPrompt:'দৈনন্দিন গণনা',gArithmeticQuestion:'আপোনাৰ ওচৰত {a}টা কাপ আছে আৰু {b}টা লগাইছে। মুঠ কিমান কাপ হ\'ল?',gAttentionPrompt:'মিল থকা চিহ্নবোৰ বিচাৰক',gAttentionQuestion:'আপুনি কিমানটা {symbol} চিহ্ন দেখা পাইছে?',
  rWakeUp:'শোৱাৰ পৰা উঠক',rBrushTeeth:'দাঁত মাজক',rEatBreakfast:'পুৱাৰ আহাৰ খাওক',rLeaveHome:'ঘৰৰ পৰা ওলাওক',rWashHands:'হাত ধুওক',rPrepareFood:'খাদ্য যুগুত কৰক',rEatMeal:'আহাৰ খাওক',rWashDishes:'বাচন-বৰ্তন ধুওক',rPutSocks:'মোজা পিন্ধক',rPutShoes:'জোতা পিন্ধক',rTieShoelaces:'জোতাৰ ফিটা বান্ধক',rGoWalk:'খোজ কাঢ়িবলৈ ওলাওক',
  answerPrefix:'উত্তৰ: ',reminderPrefix:'সোঁৱৰাই দিয়া: ',onDatePrefix:'তাৰিখ: ',streakProgress:'আপুনি {streak} দিন ধাৰাবাহিকভাৱে অনুশীলন কৰিছে আৰু {count}টা কাৰ্যকলাপ সম্পূৰ্ণ কৰিছে',unlockedLabel:'খুলিল',keepPractisingLabel:'অনুশীলন অব্যাহত ৰাখক',hearProgress:'মোৰ প্ৰগতি শুনক',
  familyHelp:'প্ৰথমে যত্নৰ সংগীত অতি কমেও দুজন চিনাকি মানুহৰ নাম আৰু বেলেগ বেলেগ সম্পৰ্ক যোগ কৰক। ৰোগীয়ে সংৰক্ষণ কৰাত সন্মতি দিয়া তথ্যহে ব্যৱহাৰ কৰক।',thanksPractising:'অনুশীলন কৰাৰ বাবে ধন্যবাদ',activitySavedNote:'আপোনাৰ কাৰ্যকলাপ সংৰক্ষণ কৰা হৈছে। এই স্ক\'ৰ কোনো চিকিৎসা মূল্যায়ন নহয়।',audioUnavailable:'অডিঅ’ উপলব্ধ নাই। আন এটা কাৰ্যকলাপ বাছক।',playNotesLabel:'▶ সুৰ শুনক',
  yourSpace:'আপোনাৰ ঠাই',editProfileTitle:'প্ৰ\'ফাইল সম্পাদনা কৰক',profileLead:'SmritiSaathi ক নিজৰ আৰু আপোনজনৰ দৰে অনুভৱ কৰাওক।',tabAccount:'একাউণ্ট',tabReports:'চিকিৎসা ইতিহাস',tabRewards:'পুৰস্কাৰ',uploadPhoto:'ফট’ আপল’ড কৰক',removeLabel:'আঁতৰাওক',fullName:'সম্পূৰ্ণ নাম',ageLabel:'বয়স',phoneLabel:'ফোন',saveChanges:'সলনিবোৰ সংৰক্ষণ কৰক',personalHelpVoice:'ব্যক্তিগত সহায় কণ্ঠধ্বনি',addYourVoice:'আপোনাৰ কণ্ঠধ্বনি যোগ কৰক',voiceNoteDesc:'এটা চুটি, চিনাকি কণ্ঠধ্বনি টোকা ৰেকৰ্ড কৰক। লাইভ যাত্ৰাৰ সময়ত ৰোগী পথৰ পৰা আঁতৰি গ\'লে, এই সংৰক্ষিত কণ্ঠধ্বনি যত্নকাৰীৰ সহায় এলাৰ্টৰ সৈতে পঠোৱা হয়।',stopRecording:'ৰেকৰ্ডিং বন্ধ কৰক',savingEllipsis:'সংৰক্ষণ কৰি থকা হৈছে…',recordAgain:'পুনৰ ৰেকৰ্ড কৰক',removeVoiceLabel:'কণ্ঠধ্বনি আঁতৰাওক',recordingHint:'ৰেকৰ্ডিং হৈ আছে… স্বাভাৱিকভাৱে কওক। ই 5 ছেকেণ্ডৰ পিছত নিজে বন্ধ হ\'ব।',yourRecords:'আপোনাৰ ৰেকৰ্ড',medicalHistoryTitle:'চিকিৎসা ইতিহাস',rewardsStreakTitle:'পুৰস্কাৰ আৰু ধাৰাবাহিক অনুশীলন',currentStreak:'ধাৰাবাহিক অনুশীলনৰ দিন',activitiesCompleted:'সম্পূৰ্ণ কৰা কাৰ্যকলাপ',practiceAccuracy:'অনুশীলনৰ সঠিকতা',badgeFirst:'প্ৰথম পদক্ষেপ',badgeFive:'৫টা কাৰ্যকলাপ',badgeTen:'১০টা কাৰ্যকলাপ',badgeStreak:'৩ দিনৰ ধাৰাবাহিকতা',
  voiceUnsupported:'এই ব্ৰাউজাৰত কণ্ঠধ্বনি ৰেকৰ্ডিং সমৰ্থিত নহয়।',voiceRecordFailed:'কণ্ঠধ্বনি ৰেকৰ্ড কৰিব পৰা নগ\'ল। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',micPermissionNeeded:'মাইক্ৰ\'ফোনৰ অনুমতিৰ প্ৰয়োজন।',voiceTooLong:'অনুগ্ৰহ কৰি এটা চুটি কণ্ঠধ্বনি টোকা ৰেকৰ্ড কৰক (সৰ্বাধিক ৫ ছেকেণ্ড)।',voiceSaveFailed:'আপোনাৰ কণ্ঠধ্বনি সংৰক্ষণ কৰিব পৰা নগ\'ল।',
  tabHome:'মোৰ ঘৰ',myHomeTitle:'মোৰ ঘৰ',myHomeDesc:'আপোনাৰ ঘৰৰ ঠিকনা ছেট কৰক। ইয়াৰ অৱস্থান তলৰ মেপত দেখা যাব।',homeAddressLabel:'ঘৰৰ ঠিকনা',homeAddressPlaceholder:'আপোনাৰ ঘৰৰ ঠিকনা বিচাৰক…',saveHomeAddress:'মোৰ ঘৰ হিচাপে সংৰক্ষণ কৰক',updateHomeAddress:'ঠিকনা সলনি কৰক',removeHomeAddress:'ঘৰ আঁতৰাওক',myHomeAlertNote:'লাইভ অৱস্থান অন থাকিলে (যাত্ৰাত), আপুনি এই ঘৰৰ পৰিসৰৰ পৰা আঁতৰি গ\'লে আপোনাৰ যত্নকাৰীলৈ এলাৰ্ট যাব।',nearHomeCue:'আপুনি ঘৰৰ ওচৰত আছে।',
  storyEyebrow:'মোৰ কাহিনীৰ সময়',storyChooseState:'এখন ৰাজ্য বাছক',storyChooseStateLead:'North-East ৰ ৮খন সিষ্টাৰ ষ্টেটৰ পৰা যিকোনো এখন ৰাজ্য বাছক আৰু তাৰ লোক-কাহিনী পঢ়ক বা শুনক।',storyBackToStates:'সকলো ৰাজ্য',storyStateSub:'{icon} · {count}টা কাহিনী',storyStoriesOf:'{state} ৰ কাহিনী',storyStorySub:'{count}টা প্ৰশ্ন · লোক-কাহিনী',storyBackToStories:'{state} ৰ কাহিনী',storyLangLabel:'পঢ়া/শুনাৰ ভাষা',storyChapterLead:'এই কাহিনীটো {count}টা চুটি অধ্যায়ত ভগোৱা হৈছে। এটা এটাকৈ পঢ়ক বা শুনক।',storyChapter:'অধ্যায় {n}',storyBackToChapters:'সকলো অধ্যায়',storyPrevChapter:'পূৰ্বৱৰ্তী অধ্যায়',storyNextChapter:'পৰৱৰ্তী অধ্যায়',storyStartQuestions:'প্ৰশ্ন আৰম্ভ কৰক',storyListenChapter:'অধ্যায় শুনক',storyPlaying:'শুনোৱা হৈ আছে…',storyQuestionLabel:'প্ৰশ্ন {n}',storyYourAnswer:'আপোনাৰ উত্তৰ',storyAnswerPlaceholder:'আপোনাৰ উত্তৰ টাইপ কৰক, বা মাইক ব্যৱহাৰ কৰক',storySubmit:'দাখিল কৰক',storyHintPrefix:'ইংগিত: ',storyGoodFeedback:'ভাল হৈছে! আপুনি শুদ্ধকৈ মনত ৰাখিছে।',storyTryFeedback:'কোনো অসুবিধা নাই, ভাল চেষ্টা আছিল! শুদ্ধ উত্তৰটো আছিল: {answer}।',storyDoneHeading:'ভাল হৈছে!',storyDoneBody:'আপুনি "{title}" সম্পূৰ্ণ পঢ়িলে/শুনিলে আৰু {count}টা প্ৰশ্নৰ উত্তৰ দিলে।',storyAnotherStory:'{state} ৰ পৰা আৰু এটা কাহিনী'
};

const kha={home:'Ka sngi jong nga',games:'Ki jingialehkai',reminders:'Ki jingpynkynmaw',journey:'Ki jaka',care:'Ki nongsumar',privacy:'Ka jingrieh',welcome:'Khublei',save:'Buh',cancel:'Pyndam',back:'Phai',listen:'Sngap',speak:'Kren',today:'Mynta',name:'Kyrteng',next:'Nangta',sos:'Pan jingiarap',done:'Long',stop:'Iohi',yes:'Ha oh',no:'Chi'};
const lus={home:'Ka ni',games:'Infiamna',reminders:'Hriattirna',journey:'Hmun leh zin kawng',care:'Enkawltu',privacy:'Mimal thil',welcome:'Chibai',save:'Dah tha',cancel:'Titawp',back:'Kir leh',listen:'Ngaithla',speak:'Saw i rawh',today:'Vawiin',name:'Hming',next:'A dawt leh',sos:'Tanpuina dil',done:'Zo tawh',stop:'Tawp'};
const mni={home:'ꯑꯩꯒꯤ ꯅꯨꯃꯤꯠ',games:'ꯁꯥꯟꯅꯄ',reminders:'ꯅꯤꯡꯁꯤꯡꯍꯟꯕ',name:'ꯃꯤꯡ',today:'ꯉꯁꯤ',listen:'ꯇꯥꯕ',speak:'ꯉꯥꯡꯕ',back:'ꯍꯜꯂꯛꯄ'};
const brx={home:'आंनि सान',games:'गेलेनाय',reminders:'गोसोखांहोनाय',name:'मुं',today:'दिनै',listen:'खोनासं',speak:'बुं',back:'उनफिन'};

export const dictionaries={en,hi,as,kha,lus,mni,brx};

// Falls back to English (never to a mismatched other language) so an
// untranslated key still reads correctly instead of showing raw text in the
// wrong script, or the bare key name.
export const translate=(lang,key)=>dictionaries[lang]?.[key]??en[key]??key;

// Same as translate(), but fills in {placeholders} — used for game
// questions and status lines that need a number/name inserted, e.g.
// tf(lang,'gFamilyQuestion',{relation:'mother'}).
export const tf=(lang,key,vars={})=>translate(lang,key).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'');
